---
title: "Figure_2_solution"
output: html_document
date: "2024-05-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(snpR); library(ggplot2); library(cowplot); source("functions.R"); library(ggblend)

# subfuncs
get_high_fst <- function(x, cut){
  x <- calc_global_fst(x, "pop")
  fst <- x@pairwise.stats[facet == "pop" & comparison == ".GLOBAL"]
  high_fst <- which(fst$fst >= quantile(fst$fst, cut, na.rm = TRUE))
  
  total_fst <- get.snpR.stats(x, "pop", "fst")$weighted.means$mean_fst
  
  x_high <- x[which(snp.meta(x)$.snp.id %in% fst$.snp.id[high_fst]),]
  
  return(list(x = x_high, total_fst = total_fst))
}

plot_pca <- function(x) {
  return(ggplot(x$data$pca, aes(x = PC1, y = PC2, color = pop)) +
           geom_point(show.legend = FALSE) +
           theme_bw() +
           xlab(paste0("PC1 (", round(x$pca_loadings[1]/sum(x$pca_loadings)*100, 2), "%)")) +
           ylab(paste0("PC2 (", round(x$pca_loadings[2]/sum(x$pca_loadings)*100, 2), "%)")) +
           scale_color_manual(values = monarch_colors))
}

plot_density <- function(x){
  return(ggplot(x$null, aes(x = delta_Fstat)) +
           geom_density(color = monarch_colors[[4]]) +
           geom_vline(xintercept = x$observed$delta_Fstat, color = monarch_colors[[2]]) +
           theme_bw() +
           xlab(bquote(Delta*italic(F))) +
           ylab("Density"))
}
colours <- khroma::color("batlow")
monarch_colors <- colours(4, range=c(0.1,0.8))
# monarch_colors <- c("#d4a85e","#eb5d2e","#829b51","#393e42")

```

# read in boot data
```{r}
keys <- c("candidate_cryptic_multi_101_boot", "ms_boot", "island_redo")
files <- lapply(keys, function(x) list.files("../results/PCA_boots/", x, full.names = TRUE))
res <- lapply(files, parse_boot_res)
p <- purrr::map(res, "p")
plots <- purrr::map(res, "plot")
```

# prep PCAs
```{r}
# random
rand <- readRDS("../data/ms_out_1.RDS")
t_a_PCA_rand <- plot_clusters(rand, "pop")
rand_high <- get_high_fst(rand, .95)
t_h_PCA_rand <- plot_clusters(rand_high$x, "pop")

# island
island <- readRDS("../data/island_sim.RDS")
t_a_PCA_island <- plot_clusters(island, "pop")
island_high <- get_high_fst(island, .95)
t_h_PCA_island <- plot_clusters(island_high$x, "pop")

# cryptic
cryptic <- readRDS("../data/candidate_cryptic_multi_101.RDS")
t_a_PCA_cryptic <- plot_clusters(cryptic, "pop")
cryptic_high <- get_high_fst(cryptic, .95)
t_h_PCA_cryptic <- plot_clusters(cryptic_high$x, "pop")


```
# distribution of F-stats
```{r}
rand_delta <- ggplot(res[[2]]$null, aes(x = delta_Fstat)) +
  geom_density() +
  geom_vline(xintercept = res[[2]]$observed$delta_Fstat, color = "red", linetype = "dashed") +
  theme_bw() +
  geom_label(data = data.frame(x = -Inf, 
                       y = Inf,
                       hjust = -.12,
                       vjust = 1.3,
                       label = paste0("p = ", round(p[[2]]["delta_Fstat"], 3))),
            aes(y = y, x = x, hjust = hjust, vjust = vjust, label = label), size = 3
  )

island_delta <- ggplot(res[[3]]$null, aes(x = delta_Fstat)) +
  geom_density() +
  geom_vline(xintercept = res[[3]]$observed$delta_Fstat, color = "red", linetype = "dashed") +
  theme_bw() +
  geom_label(data = data.frame(x = -Inf, 
                       y = Inf,
                       hjust = -.12,
                       vjust = 1.3,
                       label = paste0("p = ", round(p[[3]]["delta_Fstat"], 3))),
            aes(y = y, x = x, hjust = hjust, vjust = vjust, label = label), size = 3
  )

cryptic_delta <- ggplot(res[[1]]$null, aes(x = delta_Fstat)) +
  geom_density() +
  geom_vline(xintercept = res[[1]]$observed$delta_Fstat, color = "red", linetype = "dashed") +
  theme_bw() +
  geom_label(data = data.frame(x = -Inf, 
                       y = Inf,
                       hjust = -.12,
                       vjust = 1.3,
                       label = paste0("p = ", round(p[[1]]["delta_Fstat"], 3))),
            aes(y = y, x = x, hjust = hjust, vjust = vjust, label = label), size = 3
  )

```

# make Fig 2
```{r}

adjust_PCA_plots <- function(tplot){
  
  tplot <- ggplot(tplot$data$pca, aes(x = PC1, y = PC2, color = pop, partition = pop)) +
    geom_point(size = 1, alpha = 0.75) * (blend("lighten") + blend("multiply", alpha = 0.75)) +
    theme_bw() + 
    guides(color = "none",) +
    # geom_point(size = .1, aes(color = pop)) +
    scale_x_continuous(labels = function(x) sprintf("%.2f", x)) +
    scale_y_continuous(labels = function(x) sprintf("%.2f", x)) +
    theme(axis.title = element_text(size = 10),
          axis.text = element_text(size = 8),
          plot.title = element_text(size = 12)) +
    scale_color_manual(values = monarch_colors) +
    xlab(paste0("PC1 (", round(tplot$pca_loadings[1], 2), "%)")) +
    ylab(paste0("PC2 (", round(tplot$pca_loadings[2], 2), "%)"))
  
  return(tplot)
}

adjust_density_plots <- function(tplot){
  tplot <- tplot +
    scale_y_continuous(labels = function(x) sprintf("%.2f", x)) +
    theme(axis.title = element_text(size = 10),
          axis.text = element_text(size = 8),
          plot.title = element_text(size = 12)) +
    ylab("Density") +
    xlab(expression(Delta * italic(F)))
  return(tplot)
}


# Figure2 <- plot_grid(adjust_PCA_plots(t_a_PCA_rand$plots$pca) + 
#                        ggtitle("All SNPs"),
#                      adjust_PCA_plots(t_h_PCA_rand$plots$pca)+ 
#                        ggtitle(expression('Top' * ' ' * '5%' * ' ' *italic("F")[ST])),
#                      adjust_density_plots(rand_delta) + 
#                        ggtitle("Clustering Improvement"),
#                      
#                      adjust_PCA_plots(t_a_PCA_island$plots$pca) ,
#                      adjust_PCA_plots(t_h_PCA_island$plots$pca),
#                      adjust_density_plots(island_delta),
#                      
#                      adjust_PCA_plots(t_a_PCA_cryptic$plots$pca) ,
#                      adjust_PCA_plots(t_h_PCA_cryptic$plots$pca),
#                      adjust_density_plots(cryptic_delta),
#                      
#                      ncol = 3)


Figure2 <- plot_grid(adjust_PCA_plots(t_a_PCA_rand), # row 1: all
                     adjust_PCA_plots(t_a_PCA_island),
                     adjust_PCA_plots(t_a_PCA_cryptic),

                     # row 2: top 5%
                     adjust_PCA_plots(t_h_PCA_rand),
                     adjust_PCA_plots(t_h_PCA_island),
                     adjust_PCA_plots(t_h_PCA_cryptic),
                     
                     # row 3: clustering improvement
                     adjust_density_plots(rand_delta),
                     adjust_density_plots(island_delta),
                     adjust_density_plots(cryptic_delta),
                     ncol = 3, scale = .98, align = "hv", axis = "lrtb")
cairo_pdf("../results/Figure2.pdf", width = 7, height = 7)
Figure2
dev.off()

```

