---
title: "Supp_Figures"
output: html_document
date: "2025-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("functions.R")
library(data.table); library(ggplot2)
```

# Parsing subfunction
```{r}
small_parse_boot_res <- function(files){
  files <- lapply(files, readRDS)
  
  null <- purrr::map(files, "null_distribution")
  null <- rbindlist(null)
  
  real <- files[[1]]$observed_values
  
  p <- get_p_values(real, null[,-1], c("greater", "greater", "greater", "greater", "greater", "greater"))
  
  return(p)
}
```

# Read in and parse all of the sets of results

```{r}
model_names <- c("cryptic", "random", "low_structure")
files <- list(list.files("../results/PCA_boots/cryptic_multi/permutation", "boot_r", full.names = TRUE),
              list.files("../results/PCA_boots/no_struct_multi/permutation/", "permutation_.+_boot", full.names = TRUE),
              list.files("../results/PCA_boots/cryptic_multi/permutation", "control_boot", full.names = TRUE))
files <- lapply(files, function(x){
  tboot <- stringr::str_extract(x, "_[0-9]+_")
  tbootu <- unique(tboot)
  
  options <- vector("list", length(tbootu))
  names(options) <- gsub("_", "", tbootu)
  for(i in 1:length(tbootu)){
    options[[i]] <- x[tboot == tbootu[i]]
  }
  
  return(options)
})
res <- lapply(files, function(x){
  r <- lapply(x, small_parse_boot_res)
  rdf <- as.data.frame(r)
  rdf <- as.data.table(t(rdf))
  return(rdf)
})

names(res) <- model_names

```

# Plot
```{r}
res <- rbindlist(res, idcol = "model")
percent_sig <- res[,sum(delta_Fstat <= 0.05)/.N, by = model]
res[,`p <= 0.05` := delta_Fstat <= 0.05]

FS1 <- ggplot(res, aes(x = delta_Fstat,
                y = ifelse(after_stat(count) > 0, count/sum(count), NA))) + 
  geom_histogram(aes(color = `p <= 0.05`, fill = `p <= 0.05`), drop = TRUE) +
  geom_vline(xintercept = 0.05, color = "red") +
  facet_wrap(~factor(model, c("random", "low_structure", "cryptic")), ncol = 1) + theme_bw() +
  geom_label(data = data.frame(x = 0.05, 
                       y = Inf,
                       hjust = -.12,
                       vjust = 1.3,
                       model = model_names,
                       label = paste0(round(percent_sig$V1[match(model_names, percent_sig$model)], 3)*100, "% significant")),
            aes(y = y, x = x, hjust = hjust, vjust = vjust, label = label), size = 3) +
  xlab(bquote(italic(p)* "-" * Delta[F])) +
  ylab("Proportion of simulations") +
  scale_color_manual(values = c("black", "red")) +
  scale_fill_manual(values = c("black", "red")) +
  scale_y_continuous(expand = expansion(add = c(0, .025))) +
  theme(strip.background = element_blank())


ggsave("../results/Supplementary_Figure1.pdf", FS1, width = 6, height = 4.4)
```

